services:
  django:
    build:
      context: ./backend
      dockerfile: django.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: nuxt.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - django
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - app-net

  db:
    image: postgres:18.1
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql
    env_file:
      - .env
    networks:
      - app-net

networks:
  app-net:
    driver: bridge